# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubewall" do
  def caveats
    <<~EOS
      \e[1mTo run kubewall cli simply run:\e[0m
        \e[32mkubewall\e[0m

      \e[1mTo run kubewall on specific ip and port:\e[0m
        \e[32mkubewall --listen :7080\e[0m
    EOS
  end

  name "kubewall"
  desc "kubewall is a single binary to manage multiple clusters."
  homepage "https://github.com/kubewall/kubewall"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubewall"

  on_macos do
    url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Darwin_all.tar.gz"
    sha256 "986a70d9d9a06472fd30cd79f97beee8b080d9c651854348df6099fdae7db9a8"
  end

  on_linux do
    on_intel do
      url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Linux_x86_64.tar.gz"
      sha256 "4b04c9b360405225c3c04ea479c77143bc33031ada5a483377a44b412f7a7ce9"
    end
    on_arm do
      url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Linux_arm64.tar.gz"
      sha256 "0cc19a00015f5a46fc54d34de7ab4bb7702bce6c3e5ae2371b600d54ee92fd54"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubewall"]
    end
  end

  # No zap stanza required
end
