# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubewall" do
  def caveats
    <<~EOS
      \e[1mTo run kubewall cli simply run:\e[0m
        \e[32mkubewall\e[0m

      \e[1mTo run kubewall on specific ip and port:\e[0m
        \e[32mkubewall --listen :7080\e[0m
    EOS
  end

  name "kubewall"
  desc "kubewall is a single binary to manage multiple clusters."
  homepage "https://github.com/kubewall/kubewall"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubewall"

  on_macos do
    url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Darwin_all.tar.gz"
    sha256 "9a0514a214828bc764cf90cdc0c7d2179a4696176d9e997248a0105095386b61"
  end

  on_linux do
    on_intel do
      url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Linux_x86_64.tar.gz"
      sha256 "f6f2e72c15102a308e03b11cc854c5383cf59c7a7986b21765da7cab5d23ebc2"
    end
    on_arm do
      url "https://github.com/kubewall/kubewall/releases/download/v#{version}/kubewall_Linux_arm64.tar.gz"
      sha256 "b6b51442c7e3660cb260bba60d2fc561a1980793f763f052ad56e00c0410c1b8"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubewall"]
    end
  end

  # No zap stanza required
end
