# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubewall" do
  def caveats
    <<~EOS
      \e[1mTo run kubewall cli:\e[0m
        \e[32mkubewall\e[0m

      \e[1mTo run kubewall as a background service:\e[0m
        \e[32mbrew services start kubewall\e[0m

      \e[1mTo manage the background service:\e[0m
        \e[33mbrew services stop kubewall\e[0m
        \e[33mbrew services restart kubewall\e[0m

      \e[1mLog files are available at:\e[0m
        \e[34m/opt/homebrew/var/log/kubewall.log\e[0m
    EOS
  end
  service do
    run [opt_bin/"kubewall","--no-open-browser"]
    keep_alive true
    log_path var/"log/kubewall.log"
    error_log_path var/"log/kubewall.log"
  end

  desc "kubewall is a single binary to manage multiple clusters."
  homepage "https://github.com/kubewall/kubewall"
  version "0.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubewall"

  on_macos do
    url "https://github.com/kubewall/kubewall/releases/download/v0.0.13/kubewall_Darwin_all.tar.gz"
    sha256 "3f08130aceb91f7ff2877666de6e86cde707b917e2304a093088ea1498362700"
  end

  on_linux do
    on_intel do
      url "https://github.com/kubewall/kubewall/releases/download/v0.0.13/kubewall_Linux_x86_64.tar.gz"
      sha256 "dd76d65a049323ff73f030411567984007210e1afab0c5921783209519f484c6"
    end
    on_arm do
      url "https://github.com/kubewall/kubewall/releases/download/v0.0.13/kubewall_Linux_arm64.tar.gz"
      sha256 "bf8bde976316624fb95620b9156698be0bec485f99f47758f7f6af03c95e2b24"
    end
  end

  conflicts_with formula: [
      "kubewall",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubewall"]
    end
  end

  # No zap stanza required
end
