# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubewall < Formula
  desc "kubewall is a single binary to manage multiple clusters."
  homepage "https://github.com/kubewall/kubewall"
  version "0.0.2"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/kubewall/kubewall/releases/download/v0.0.2/kubewall_Darwin_all.tar.gz"
    sha256 "6ee87423cc179e751b6a36fa590a25e755f257c2320b502b1af7edd0788653d0"

    def install
      bin.install "kubewall"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubewall/kubewall/releases/download/v0.0.2/kubewall_Linux_x86_64.tar.gz"
        sha256 "889bf292b3197f49286044106be0b3b103b77dbe4efa6fdcba26659c88965e4e"

        def install
          bin.install "kubewall"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubewall/kubewall/releases/download/v0.0.2/kubewall_Linux_arm64.tar.gz"
        sha256 "37a0919d0f81927db945cf6662e63fcd3c36343e15f143508216cc1e9a52dbd7"

        def install
          bin.install "kubewall"
        end
      end
    end
  end

  test do
    system "#{bin}/kubewall -v"
  end
end
