# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubewall < Formula
  desc "kubewall is a single binary to manage multiple clusters."
  homepage "https://github.com/kubewall/kubewall"
  version "0.0.10"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/kubewall/kubewall/releases/download/v0.0.10/kubewall_Darwin_all.tar.gz"
    sha256 "ea2dd1e4bacb5f8aa98d5b97136cddaf194dbf0010625529e27c9729c7c76776"

    def install
      bin.install "kubewall"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubewall/kubewall/releases/download/v0.0.10/kubewall_Linux_x86_64.tar.gz"
        sha256 "58b45a920c007159ff66e9d32bc0299b3ce775a15f0b878eb7b862752c3de942"

        def install
          bin.install "kubewall"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubewall/kubewall/releases/download/v0.0.10/kubewall_Linux_arm64.tar.gz"
        sha256 "5a76ba33eae3325933fb9e75c4d90376110f3d4197448e5193a864f17b7d88c5"

        def install
          bin.install "kubewall"
        end
      end
    end
  end

  test do
    system "#{bin}/kubewall -v"
  end
end
